name: meal_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  google_nav_bar: ^5.0.6
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo/cheff logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Categories/asian category.jpeg
    - assets/images/Categories/breakfast category.jpeg
    - assets/images/Categories/exotic category.png
    - assets/images/Categories/french category.jpeg
    - assets/images/Categories/german category.jpg
    - assets/images/Categories/italian category.png
    - assets/images/Categories/lovely category.png
    - assets/images/Categories/quick category.jpeg
    - assets/images/Categories/summer category.jpeg
    - assets/images/Categories/hamburgers category.png
    - assets/images/Meals/Bistecca Alla Fiorentina.jpeg
    - assets/images/Meals/Lasagne.jpeg
    - assets/images/Meals/Muffin.jpeg
    - assets/images/Meals/Pan-fried camembert sandwich.jpeg
    - assets/images/Meals/Risotto.jpeg
    - assets/images/Meals/Spaghetti with Tomato Sauce.jpeg
    - assets/images/Meals/Taco.jpeg
    - assets/images/Meals/Toast Hawaii.jpeg
    - assets/images/Meals/asparagus-3304997_1280.jpg
    - assets/images/Meals/burger-500054_1280.jpg
    - assets/images/Meals/indian-food-3482749_1280.jpg
    - assets/images/Meals/orange .jpg
    - assets/images/Meals/pancake-3529653_1280.jpg
    - assets/images/Meals/schnitzel-3279045_1280.jpg
    - assets/images/Meals/smoked-salmon-salad-1768890_1280.jpg
    - assets/images/Meals/souffle-412785_1280.jpg
    - assets/images/Meals/turky burger.jpeg
    - assets/images/Meals/Bean burger.jpeg
    - assets/images/Meals/Veggie burger.jpeg
    - assets/images/Meals/Labskaus.jpeg
    - assets/images/Meals/Königsberger klopse.jpeg
    - assets/images/Meals/Käsespätzle.jpeg
    - assets/images/Meals/Tossed salad.jpeg
    - assets/images/Meals/Palak Dal Khichdi.jpeg
    - assets/images/Meals/Low-Calorie Oats Idli.jpeg
    - assets/images/Logo/cheff logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

    - family: Gilory
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Regular-Copy.ttf
